/**
 * generateCode — pure graph → SovereignClaw TypeScript source.
 *
 * Contract (per spec §11.3): same graph always produces the same code,
 * byte-for-byte. This is important because:
 *   1. Snapshot tests guard against drift.
 *   2. The backend re-runs `generateCode(graph)` after receiving the
 *      graph and diffs against the client's preview; any mismatch aborts
 *      the deploy (audit trail).
 *   3. Manifest hash embeds the generated code, so changes are
 *      cryptographically visible.
 *
 * Output program shape:
 *   1. Imports from @sovereignclaw/{core,memory,mesh,reflection}.
 *   2. Agent factory functions per Agent node.
 *   3. `main()` that builds memory/inference/reflection, wires agents,
 *      and either runs `planExecuteCritique` for a Mesh or `agent.run()`
 *      for a single-agent graph.
 *   4. A bottom-of-file `main().catch(...).` so the program is runnable
 *      under `tsx` or after `tsc`.
 *
 * The generator does NOT try to be ultra-clever — readability beats
 * cleverness, because users will copy this code.
 */
import type {
  AgentNodeData,
  InferenceNodeData,
  MemoryNodeData,
  MeshNodeData,
  ReflectionNodeData,
  StudioEdge,
  StudioGraph,
  StudioNode,
} from './types.js';

export interface GenerateCodeResult {
  source: string;
  /** Imported symbols per package — used by esbuild to detect dead imports. */
  imports: Record<string, string[]>;
}

const INDENT = '  ';

/** Deterministic ordering — sort by node id. */
function sortedNodes(graph: StudioGraph): StudioNode[] {
  return [...graph.nodes].sort((a, b) => a.id.localeCompare(b.id));
}

function findEdges(graph: StudioGraph, target: StudioNode, role: string): StudioEdge[] {
  return graph.edges.filter((e) => e.target === target.id && e.edgeRole === role);
}

function jsonStr(v: unknown): string {
  return JSON.stringify(v);
}

function varName(prefix: string, id: string): string {
  const clean = id.replace(/[^a-zA-Z0-9]/g, '_');
  return `${prefix}_${clean}`;
}

export function generateCode(graph: StudioGraph): GenerateCodeResult {
  const imports: Record<string, string[]> = {
    '@sovereignclaw/core': [],
    '@sovereignclaw/memory': [],
    '@sovereignclaw/reflection': [],
    '@sovereignclaw/mesh': [],
  };
  const addImport = (pkg: keyof typeof imports, sym: string): void => {
    const list = imports[pkg] ?? (imports[pkg] = []);
    if (!list.includes(sym)) list.push(sym);
  };

  const lines: string[] = [];
  const push = (s = ''): void => {
    lines.push(s);
  };

  push('/**');
  push(' * Auto-generated by ClawStudio. Do not edit by hand.');
  push(' *');
  push(` * Nodes: ${graph.nodes.length}, edges: ${graph.edges.length}.`);
  push(' * Regenerate by re-exporting from ClawStudio or via the');
  push(' * `generateCode(graph)` pure function in @sovereignclaw/studio.');
  push(' */');
  push("import { config as loadDotenv } from 'dotenv';");
  push('loadDotenv();');
  push("import { JsonRpcProvider, Wallet } from 'ethers';");
  push('');

  // Imports will be emitted after we know what's used. Leave a placeholder.
  const importsPlaceholder = lines.length;
  push(''); // placeholder line 1
  push(''); // placeholder line 2
  push(''); // placeholder line 3
  push(''); // placeholder line 4

  addImport('@sovereignclaw/memory', 'deriveKekFromSigner');
  addImport('@sovereignclaw/memory', 'encrypted');
  addImport('@sovereignclaw/memory', 'OG_Log');
  addImport('@sovereignclaw/core', 'Agent');
  addImport('@sovereignclaw/core', 'sealed0GInference');

  push('function required(name: string): string {');
  push(`${INDENT}const v = process.env[name];`);
  push(`${INDENT}if (!v) throw new Error('missing env ' + name);`);
  push(`${INDENT}return v;`);
  push('}');
  push('');

  push('async function main(): Promise<void> {');
  push(`${INDENT}const RPC_URL = required('RPC_URL');`);
  push(`${INDENT}const INDEXER_URL = required('INDEXER_URL');`);
  push(`${INDENT}const PRIVATE_KEY = required('PRIVATE_KEY');`);
  push(`${INDENT}const ROUTER_URL = required('COMPUTE_ROUTER_BASE_URL');`);
  push(`${INDENT}const ROUTER_KEY = required('COMPUTE_ROUTER_API_KEY');`);
  push(`${INDENT}const MODEL_DEFAULT = process.env.COMPUTE_MODEL ?? 'qwen/qwen-2.5-7b-instruct';`);
  push('');
  push(`${INDENT}const provider = new JsonRpcProvider(RPC_URL);`);
  push(`${INDENT}const signer = new Wallet(PRIVATE_KEY, provider);`);
  push('');

  const nodes = sortedNodes(graph);

  // 1. Memory nodes.
  const memoryVars = new Map<string, string>();
  for (const n of nodes) {
    if (n.data.kind !== 'memory') continue;
    const m = n.data as MemoryNodeData;
    const v = varName('memory', n.id);
    const kekExpr = `await deriveKekFromSigner(signer, ${jsonStr(m.namespace)})`;
    const providerExpr = `OG_Log({ namespace: ${jsonStr(m.namespace)}, rpcUrl: RPC_URL, indexerUrl: INDEXER_URL, signer })`;
    if (m.encrypted) {
      push(`${INDENT}const ${v}_kek = ${kekExpr};`);
      push(`${INDENT}const ${v} = encrypted(${providerExpr}, { kek: ${v}_kek });`);
    } else {
      push(`${INDENT}const ${v} = ${providerExpr};`);
    }
    memoryVars.set(n.id, v);
  }
  if (memoryVars.size > 0) push('');

  // 2. Inference nodes.
  const inferenceVars = new Map<string, string>();
  for (const n of nodes) {
    if (n.data.kind !== 'inference') continue;
    const i = n.data as InferenceNodeData;
    const v = varName('inference', n.id);
    push(`${INDENT}const ${v} = sealed0GInference({`);
    push(`${INDENT}${INDENT}model: ${jsonStr(i.model)},`);
    push(`${INDENT}${INDENT}apiKey: ROUTER_KEY,`);
    push(`${INDENT}${INDENT}baseUrl: ROUTER_URL,`);
    push(`${INDENT}${INDENT}verifiable: ${i.verifiable ? 'true' : 'false'},`);
    push(`${INDENT}});`);
    inferenceVars.set(n.id, v);
  }
  if (inferenceVars.size > 0) push('');

  // 3. Reflection nodes.
  const reflectionVars = new Map<string, string>();
  let hasReflection = false;
  for (const n of nodes) {
    if (n.data.kind !== 'reflection') continue;
    hasReflection = true;
    const r = n.data as ReflectionNodeData;
    const v = varName('reflect', n.id);
    push(`${INDENT}const ${v} = reflectOnOutput({`);
    push(`${INDENT}${INDENT}rounds: ${r.rounds},`);
    push(`${INDENT}${INDENT}critic: ${jsonStr(r.critic === 'self' ? 'self' : 'self')},`);
    push(`${INDENT}${INDENT}rubric: ${jsonStr(r.rubric)},`);
    push(`${INDENT}${INDENT}threshold: ${r.threshold},`);
    push(`${INDENT}${INDENT}persistLearnings: ${r.persistLearnings ? 'true' : 'false'},`);
    push(`${INDENT}});`);
    reflectionVars.set(n.id, v);
  }
  if (hasReflection) {
    addImport('@sovereignclaw/reflection', 'reflectOnOutput');
    push('');
  }

  // 4. Agent nodes, wired from edges.
  const agentVars = new Map<string, string>();
  for (const n of nodes) {
    if (n.data.kind !== 'agent') continue;
    const a = n.data as AgentNodeData;
    const v = varName('agent', n.id);

    const memoryEdge = findEdges(graph, n, 'memory')[0];
    const historyEdge = findEdges(graph, n, 'history')[0];
    const inferenceEdge = findEdges(graph, n, 'inference')[0];
    const reflectEdge = findEdges(graph, n, 'reflect')[0];

    const inferenceVar = inferenceEdge ? inferenceVars.get(inferenceEdge.source) : undefined;
    if (!inferenceVar) {
      push(`${INDENT}// TODO: agent '${a.role}' missing inference wiring — codegen emits a stub`);
    }

    push(`${INDENT}const ${v} = new Agent({`);
    push(`${INDENT}${INDENT}role: ${jsonStr(a.role)},`);
    push(`${INDENT}${INDENT}systemPrompt: ${jsonStr(a.systemPrompt)},`);
    push(`${INDENT}${INDENT}inference: ${inferenceVar ?? '/* unwired */ undefined as any'},`);
    if (memoryEdge) {
      const memVar = memoryVars.get(memoryEdge.source);
      if (memVar) push(`${INDENT}${INDENT}memory: ${memVar},`);
    }
    if (historyEdge) {
      const histVar = memoryVars.get(historyEdge.source);
      if (histVar) push(`${INDENT}${INDENT}history: ${histVar},`);
    }
    if (reflectEdge) {
      const refVar = reflectionVars.get(reflectEdge.source);
      if (refVar) push(`${INDENT}${INDENT}reflect: ${refVar},`);
    }
    push(`${INDENT}});`);
    agentVars.set(n.id, v);
  }
  if (agentVars.size > 0) push('');

  // 5. Mesh node (zero or one for v0).
  const meshNodes = nodes.filter((n) => n.data.kind === 'mesh');
  if (meshNodes.length > 1) {
    // Validator should catch this; keep a comment.
    push(`${INDENT}// NOTE: graph has ${meshNodes.length} mesh nodes; v0 emits only the first.`);
  }
  const meshNode = meshNodes[0];

  if (meshNode) {
    addImport('@sovereignclaw/mesh', 'Mesh');
    addImport('@sovereignclaw/mesh', 'planExecuteCritique');
    addImport('@sovereignclaw/memory', 'InMemory');
    const m = meshNode.data as MeshNodeData;
    const meshVar = varName('mesh', meshNode.id);
    push(`${INDENT}const ${meshVar} = new Mesh({`);
    push(`${INDENT}${INDENT}meshId: ${jsonStr(m.meshId)},`);
    // InMemory bus for v0; users can swap to encrypted(OG_Log()) in the editor.
    push(`${INDENT}${INDENT}provider: InMemory({ namespace: ${jsonStr(`${m.meshId}-bus`)} }),`);
    push(`${INDENT}});`);
    push('');

    const plannerEdge = findEdges(graph, meshNode, 'planner')[0];
    const criticEdge = findEdges(graph, meshNode, 'critic')[0];
    const executorEdges = findEdges(graph, meshNode, 'executor');
    const plannerVar = plannerEdge && agentVars.get(plannerEdge.source);
    const criticVar = criticEdge && agentVars.get(criticEdge.source);
    const executorVars = executorEdges
      .map((e) => agentVars.get(e.source))
      .filter((v): v is string => Boolean(v));

    if (plannerVar && criticVar && executorVars.length > 0) {
      push(`${INDENT}${meshVar}.register(${plannerVar}).register(${criticVar});`);
      for (const ev of executorVars) push(`${INDENT}${meshVar}.register(${ev});`);
      push('');
      push(`${INDENT}const result = await planExecuteCritique({`);
      push(`${INDENT}${INDENT}mesh: ${meshVar},`);
      push(`${INDENT}${INDENT}planner: ${plannerVar},`);
      push(`${INDENT}${INDENT}executors: [${executorVars.join(', ')}],`);
      push(`${INDENT}${INDENT}critic: ${criticVar},`);
      push(`${INDENT}${INDENT}task: ${jsonStr(m.task)},`);
      push(`${INDENT}${INDENT}maxRounds: ${m.maxRounds},`);
      push(`${INDENT}${INDENT}acceptThreshold: ${m.acceptThreshold},`);
      push(`${INDENT}});`);
      push('');
      push(`${INDENT}console.log('\\n=== mesh result ===');`);
      push(`${INDENT}console.log(result.finalOutput);`);
      push(`${INDENT}console.log('score:', result.score, 'rounds:', result.rounds);`);
    } else {
      push(`${INDENT}// mesh not fully wired; nothing to run`);
    }

    // close + cleanup
    const allAgentVars = [...agentVars.values()];
    if (allAgentVars.length > 0) {
      push('');
      push(`${INDENT}await Promise.all([${allAgentVars.map((v) => `${v}.close()`).join(', ')}]);`);
    }
    push(`${INDENT}await ${meshVar}.close();`);
  } else if (agentVars.size === 1) {
    // Single-agent example: run once on a sample prompt.
    const only = [...agentVars.values()][0]!;
    push(
      `${INDENT}const out = await ${only}.run('What year was the Transformer paper published?');`,
    );
    push(`${INDENT}console.log(out?.text);`);
    push(`${INDENT}await ${only}.close();`);
  }

  push('}');
  push('');
  push('main().catch((err) => {');
  push(`${INDENT}console.error(err);`);
  push(`${INDENT}process.exit(1);`);
  push('});');
  push('');

  // Now render the imports block at the placeholder.
  const importLines: string[] = [];
  for (const pkg of Object.keys(imports) as (keyof typeof imports)[]) {
    const syms = imports[pkg] ?? [];
    if (syms.length === 0) continue;
    const sorted = [...syms].sort();
    importLines.push(`import { ${sorted.join(', ')} } from '${pkg}';`);
  }
  // Replace the 4 placeholder lines with the real imports + one blank.
  lines.splice(importsPlaceholder, 4, ...importLines, '');

  return { source: lines.join('\n'), imports };
}
